name: telepay-dart

repository: https://github.com/telepay/telepay-dart

packages:
  - apps/**
  - packages/**

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    # # Only allow versioning to happen on main branch.
    # branch: main
    # Additionally build a changelog at the root of the workspace.
    workspaceChangelog: true

scripts:
  analyze:
    run: melos exec -c 1 -- "flutter analyze . --fatal-infos"
    description: Run analyzer.
  test:
    run: melos exec --ignore="*example*" --concurrency=1 -- "flutter test --reporter expanded"
    description: Run tests.
    