name: telepay_http_example
description: Example using telepay_http.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  http: ^0.13.4
  telepay_http:
    path: ../../telepay_http

dev_dependencies:
  coverage: ^1.1.0
  mocktail: ^0.2.0
  test: ^1.19.2
  very_good_analysis: ^2.4.0
